Error while training using GPU (#11)
Summary:
While training a model, encountered the following errors:

```
TypeError: FloatClassNLLCriterion_updateOutput received an invalid combination of arguments - got (int, torch.FloatTensor, torch.cuda.LongTensor, torch.FloatTensor, bool, NoneType, torch.FloatTensor, int), but expected (int state, torch.FloatTensor input, torch.LongTensor target, torch.FloatTensor output, bool sizeAverage, [torch.FloatTensor weights or None], torch.FloatTensor total_weight, int ignore_index)

RuntimeError: expected CPU tensor (got CUDA tensor)
```
Two fixes are needed:
train_model.py: add the cuda() method when device is GPU
convnet.py: convert imgs tensor to CUDA tensor in the train() function + similar changes in the _test() function
Pull Request resolved: https://github.com/facebookresearch/adversarial_image_defenses/pull/11

Differential Revision: D13751088

Pulled By: lvdmaaten

fbshipit-source-id: 451926393a6206259f07b5788aa06eaeb649ba8e